blank_issues_enabled: false
contact_links:
  - name: Roam Help Database
    url: https://roamresearch.com/#/app/help/page/1wnq-ZAAN
    about: You can find help for using Roam here.
  - name: Slack
    url: https://roamresearch.slack.com/join/shared_invite/enQtODg3NjIzODEwNDgwLTdhMjczMGYwN2YyNmMzMDcyZjViZDk0MTA2M2UxOGM5NTMxNDVhNDE1YWVkNTFjMGM4OTE3MTQ3MjEzNzE1MTA
    about: Hang out with fellow Roamans here.